### ISSUE TITLE
Installing and auto-updating the script

### ISSUE THREAD

**Issue by UncleBob800** [45026831/hh-style-tweaks#5]
I propose to change the principle of installing and updating the script to how it is used in this mod [redacted]
As I understand it, the whole magic lies in the fact that if the file name ends in `.user.js`, then such a file is automatically sent to the Tampermonkey plugin for installation, reinstallation or update.
The script of that mod contains the following lines
```
// @updateURL    [redacted].user.js
// @downloadURL  [redacted].user.js
```

I also suggest these lines:
```
// @match           https://www.hentaiheroes.com/*
// @match           https://nutaku.haremheroes.com/*
// @match           https://eroges.hentaiheroes.com/*
// @match           https://thrix.hentaiheroes.com/*
// @match           https://www.gayharem.com/*
// @match           https://nutaku.gayharem.com/*
// @match           https://www.comixharem.com/*
// @match           https://nutaku.comixharem.com/*
```
Replace with these lines:
```
// @match           https://*.hentaiheroes.com/*
// @match           https://*.haremheroes.com/*
// @match           https://*.gayharem.com/*
// @match           https://*.comixharem.com/*
```
This will make your script more versatile and will allow it to work on all version of the game (including the test server, which was not listed in the list of links)

**Comment by 45026831** [comment]
Do not link to automation scripts that violate ToU from my repos, please. The installation instructions and things will be changing soon anyway, but HH++ will change before Style Tweaks.
