### ISSUE TITLE
Trouble with moveSkipButton option

### ISSUE THREAD

**Issue by UncleBob800** [45026831/hh-style-tweaks#6]
For some reason, `moveSkipButton` conflicts with the **Hentai Heroes++ (OCD) Season version** mod.
The button just doesn't appear.
I suggest these lines:
```
    if (config.moveSkipButton) {
        sheet.insertRule(`
            #new_battle #new-battle-skip-btn {
                position: relative;
                top: 388px;
                z-index: 20;
            }
        `)
    }
```
Replace with these lines:
```
    if (config.moveSkipButton) {
        sheet.insertRule(`
            #new_battle .new-battle-buttons-container {
                align-self: flex-end;
                z-index: 20;
            }
        `)
    }
```
(at least I've always used these lines in my little css modification to move the button down after this silly developer update)

**Comment by 45026831** [comment]
Tom's version of the script already moves the skip button down, so if using style tweaks with it, simply turn that tweak off. It'll be moved out of Style Tweaks into my version of HH++ in a future update.
