### ISSUE TITLE
Simplify installation and updation

### ISSUE THREAD

**Issue by UncleBob800** [45026831/hh-style-tweaks#7]
Hi. Can you rename `hh-style-tweaks.js` to `hh-style-tweaks.user.js` so that Tampermonkey can immediately install the script when user open RAW? This would make it much easier for users to install and update the script.
https://user-images.githubusercontent.com/86453893/144723816-a353ba54-b9b6-4164-b56c-97f134ef7907.mp4
Also, please add the line `// @namespace		https://github.com/45026831/hh-style-tweaks` so that user can go directly to your github page from the Control panel in Tampermonkey.
![image](https://user-images.githubusercontent.com/86453893/144723832-266245a4-a75b-41ff-850f-ca3bd42fafd4.png)

**Comment by 45026831** [comment]
Done in v0.5.1 (39aaf4a)
